[profile.default]
optimizer_runs = 1000000
verbosity = 1
remappings = [
    "seaport-types/=lib/seaport-types/"
]
solc = "0.8.20"

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4