[profile.default]
optimizer_runs = 1_000_000
verbosity = 1
remappings = ["seaport-types/=lib/seaport-types/"]
solc = "0.8.20"

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4

[rpc_endpoints]
# mainnets
mainnet = "https://rpc.ankr.com/eth"
polygon = "https://polygon.llamarpc.com"

# testnets
goerli = "https://rpc.ankr.com/eth_goerli"
sepolia = "https://ethereum-sepolia.publicnode.com"
